CREATE SCHEMA IF NOT EXISTS spotmoneydemo
CREATE TABLE IF NOT EXISTS spotmoneydemo.customer_mst
(
    customer_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_name character(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT customer_mst_pkey PRIMARY KEY (customer_id)
)

INSERT INTO spotmoneydemo.customer_mst(customer_name) values ('ABC');
INSERT INTO spotmoneydemo.customer_mst(customer_name) values ('XYZ');

